fixtures:
  repositories:
    apt: 'https://github.com/puppetlabs/puppetlabs-apt.git'
    augeas: 'https://github.com/camptocamp/puppet-augeas.git'
    augeasproviders_core: 'https://github.com/hercules-team/augeasproviders_core.git'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    puppetserver: "#{source_dir}"
